'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('ge-control-token')||'';
if(token)sessionStorage.setItem('ge-control-token',token);history.replaceState(null,'',location.pathname);
let catalog=null,checked=null,busy=false,active=false,selectedJob=null,selectedRun=null,result=null,selectionVersion=0,resultGeneration=0,plotGeneration=0;
let modelPreviewGeneration=0,modelPreviewUrl=null,importGeneration=0;
const continuationNames=new Map();
const stageNames={geometry:'Geometry and source',radiation:'Radiation transport',event_ledger:'Event ledger',response:'Fields, charge, calibration and readout',results:'Verified results'};
const stateNames={dispatch_uncertain:'Inspection required',running:'Running',stop_requested:'Stop requested',stopped:'Stopped at stage boundary',completed:'Completed',completed_with_native_failures:'Completed with native failures',inspected_failure:'Inspected denied launch · preserved',verified_transport:'Verified transport · original failure preserved'};
const labels={shaping_tau_us:['Shaping time','µs'],gain:['Shaper gain','V/V'],threshold_V:['Peak threshold','V'],adc_bits:['Peak ADC bits','bits'],adc_full_scale_V:['Peak ADC full scale','V'],feedback_capacitance_pF:['Feedback capacitance','pF'],feedback_tau_us:['Feedback decay','µs'],pole_zero_tau_us:['Pole-zero time','µs'],peak_policy:['Peak policy',''],peak_gate_start_ns:['Peak gate start','ns; blank = none'],peak_gate_end_ns:['Peak gate end','ns; blank = none']};
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'X-Control-Token':token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error||'Local action failed.');return v;}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className='notice '+(error?'error':'okay');}
function options(id,items,inspection=false){const s=$(id);s.replaceChildren();for(const item of items){const suffix=inspection?(item.available?' · Compute supported':' · View only'):item.available===false?' · '+item.reason:'';const o=node('option',item.label+suffix);o.value=item.id;o.disabled=!inspection&&item.available===false;s.append(o);}}
function currentDetector(){return catalog?.detectors.find(d=>d.id===$('detector').value);}
function currentSource(){return catalog?.sources.find(s=>s.id===$('source').value);}
function executableSelection(){const d=currentDetector();return d?.available===true&&currentSource()?.available!==false&&d.sources.includes($('source').value)&&catalog.cryostats.some(c=>c.id===$('cryostat').value&&c.available===true);}
function config(){const electronics={};for(const key of catalog.electronics_keys){const value=$('setting-'+key).value;electronics[key]=key.startsWith('peak_gate_')&&!$('use-peak-gate').checked?null:key==='peak_policy'?value:value===''?null:Number(value);}return {name:$('name').value,cryostat:$('cryostat').value,detector:$('detector').value,source:$('source').value,pose:$('pose').value,primary_count:Number($('count').value),seed:Number($('seed').value),threads:Number($('threads').value),electronics};}
function invalidate(){selectionVersion++;checked=null;$('checked-plan').textContent=executableSelection()?'Selection changed. Check the new plan.':'Viewing catalog geometry. No computation plan is available for this model.';showSelection();controls();}
function controls(){const runnable=executableSelection();for(const id of ['check','save'])$(id).disabled=busy||active||!runnable;$('load').disabled=busy||active;$('start').disabled=busy||active||!runnable||!checked;
for(const id of ['cryostat','source','pose','count','threads','name','use-peak-gate'])$(id).disabled=!runnable;$('seed').disabled=!runnable||currentSource()?.fixed_seed!=null;for(const key of catalog?.electronics_keys||[])$('setting-'+key).disabled=!runnable||key.startsWith('peak_gate_')&&!$('use-peak-gate').checked;}
function sourceLabel(id){return catalog?.sources.find(s=>s.id===id)?.label||id;}
function detectorChanged(){const previous=$('source').value,d=currentDetector(),sources=catalog.sources.filter(s=>d.sources.includes(s.id));options('source',sources);$('source').value=sources.some(s=>s.id===previous)?previous:sources[0]?.id||'';$('operating-details').textContent=d.operating_label||'';showModel(d);sourceChanged();}
function showModel(d){const m=d.model||{},count=catalog.detectors.filter(x=>x.available===true).length;
$('catalog-counts').textContent=catalog.detectors.length+' catalog models can be inspected; '+count+' have supported local computation connectors. The public website shows saved results.';
$('model-capability').textContent=d.available?'Computation supported for the listed sources. Check plan before Run.':'View only · Computation for the LBNL assembly is pending. Check, Run and export are unavailable.';$('model-capability-details').textContent=d.reason||d.operating_label||'';
$('model-title').textContent=d.id;$('model-summary').textContent=[d.type_label,m.group,m.status,m.coordinate_system?m.coordinate_system+' coordinates':''].filter(Boolean).join(' · ');
$('model-contact-summary').textContent=(m.contacts||[]).length+' contacts · catalog readout contact '+(m.readout_contact_id??'unavailable');$('model-contact-list').open=(m.contacts||[]).length<=8;$('model-contacts').replaceChildren();$('model-contacts').tabIndex=(m.contacts||[]).length>8?0:-1;for(const c of m.contacts||[])$('model-contacts').append(node('li','Contact '+c.id+' · '+c.name+' · '+(c.potential_V>0?'+':'')+c.potential_V+' V'+(c.id===m.readout_contact_id?' · catalog readout':'')));
$('model-assumptions').textContent=(m.assumptions||[]).join(' ');$('model-variant').textContent=d.id==='GeRC02'?'Preview: frozen catalog Ge30min base. Computation: separate Li50min variant at 553.15 K; stored 78 K, runtime 77 K; fresh fields.':'';
$('model-identity').textContent=JSON.stringify(m,null,2);$('model-view').href=d.geometry_url||'';$('model-view').hidden=!d.geometry_url;loadModelPreview(d);}
async function loadModelPreview(d){const generation=++modelPreviewGeneration;if(modelPreviewUrl){URL.revokeObjectURL(modelPreviewUrl);modelPreviewUrl=null;}$('model-preview-box').hidden=true;$('model-preview').removeAttribute('src');$('model-preview-status').textContent='Loading saved catalog geometry…';
try{const r=await fetch('/api/model-preview?'+new URLSearchParams({model:d.id}),{headers:{'X-Control-Token':token},cache:'no-store'});if(!r.ok)throw Error('Saved preview unavailable here. Use Open saved rotatable geometry on the public website.');const blob=await r.blob();if(generation!==modelPreviewGeneration||currentDetector()?.id!==d.id)return;modelPreviewUrl=URL.createObjectURL(blob);$('model-preview').src=modelPreviewUrl;$('model-preview').alt=d.id+' saved catalog geometry';$('model-preview-box').hidden=false;$('model-preview-status').textContent='Saved geometry · no calculation ran.';}catch(e){if(generation===modelPreviewGeneration)$('model-preview-status').textContent=e.message;}}
function showSelection(){if(!catalog)return;$('setup-preview').textContent=executableSelection()?'Current setup · '+$('detector').value+' · '+sourceLabel($('source').value)+' · '+$('count').value+' initial primaries · '+$('threads').value+' Julia threads':'Inspecting catalog model · '+$('detector').value+' · view only; no source or computation selected';}
function showRun(job){const changed=selectedJob!==job.name||selectedRun?.configuration_sha256!==job.configuration_sha256;if(changed){resultGeneration++;plotGeneration++;result=null;$('result').hidden=true;$('plots').replaceChildren();}selectedJob=job.name;selectedRun=job;$('selected').textContent='Selected run · '+job.name+' · '+job.selection.detector+' · '+sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' initial primaries';$('run-plan').textContent=JSON.stringify({configuration_sha256:job.configuration_sha256,selection:job.selection},null,2);stageList(job.stages);responseProgress(job);}
function sourceChanged(){const s=currentSource();if(!s){options('pose',[]);options('count',[]);$('source-details').textContent='A source cannot be selected until this detector has a checked computation connector.';$('source-identity').textContent='';invalidate();return;}options('pose',[{id:s.pose,label:s.pose_label||s.pose}]);options('count',s.counts.map(n=>({id:String(n),label:String(n)})));$('seed').disabled=s.fixed_seed!=null;if($('seed').disabled)$('seed').value=String(s.fixed_seed);$('source-details').textContent=[s.details||s.reason,s.count_unit?'Count unit: '+s.count_unit+'.':null,s.position_global_mm?'Position ['+s.position_global_mm.join(', ')+'] mm in the global frame.':null].filter(Boolean).join(' ');$('source-identity').textContent=JSON.stringify({source_id:s.id,count_unit:s.count_unit,position_global_mm:s.position_global_mm,source_contract:s.source_contract,acceptance:s.acceptance},null,2);invalidate();}

function electronics(){for(const key of catalog.electronics_keys){const [name,unit]=labels[key],label=node('label',name+(unit?' · '+unit:''));let input;if(key==='peak_policy'){input=node('select');for(const [value,text] of [['signed_input_positive_peak','Signed input, positive peak'],['legacy_reject_negative_input','Reject negative input']]){const o=node('option',text);o.value=value;input.append(o);}}else{input=node('input');input.type='number';input.step=key==='adc_bits'?'1':'any';}input.id='setting-'+key;label.htmlFor=input.id;input.value=catalog.electronics_defaults[key]??'';input.addEventListener('input',invalidate);label.append(input);$('electronics').append(label);}gateFields();}
function gateFields(){for(const key of ['peak_gate_start_ns','peak_gate_end_ns'])$('setting-'+key).disabled=!$('use-peak-gate').checked;}
$('use-peak-gate').onchange=()=>{gateFields();invalidate();};
function stageList(stages={}){$('pipeline').replaceChildren();for(const [key,title] of Object.entries(stageNames)){const r=stages[key],row=node('div',undefined,'stage '+(r?.status||''));row.append(node('span',undefined,'dot'));const titleBox=node('div',title,'stage-title');titleBox.append(node('small',r?.reuse==='verified_transport_prefix'?(typeof r.original_elapsed_seconds==='number'?'Reused · originally '+r.original_elapsed_seconds.toFixed(2)+' s':'Reused · saved artifacts verified; original execution time unavailable'):typeof r?.elapsed_seconds==='number'?r.elapsed_seconds.toFixed(2)+' s observed':r?.status==='completed'?'Completed · saved receipt':'Waiting for execution'));row.append(titleBox,node('span',r?.reuse==='verified_transport_prefix'?'Reused':r?.status==='completed'?'Completed':r?.status?.replaceAll('_',' ')||'Pending','pill'));$('pipeline').append(row);}}
function responseProgress(job){const p=job.response_progress;$('response-progress').textContent=p?'Native stage: '+p.stage.replaceAll('_',' ')+' · '+p.status+(p.expected_primary_count!==null?' · '+p.completed_primary_count+'/'+p.expected_primary_count+' original primaries':'')+' · '+p.elapsed_seconds.toFixed(2)+' s observed':'';}
function action(label,fn){const b=node('button',label);b.onclick=async()=>{b.disabled=true;try{await fn();await poll();}catch(e){notice(e.message,true);}finally{if(b.isConnected)b.disabled=false;}};return b;}
async function artifact(name,file,rawDownload=false){const r=await fetch('/api/workflow-file?'+new URLSearchParams({name,file,...(rawDownload?{download:'1'}:{})}),{headers:{'X-Control-Token':token},cache:'no-store'});if(!r.ok){const e=await r.json();throw Error(e.error||'Artifact unavailable.');}return r;}
async function download(name,file){const r=await artifact(name,file,true),blob=await r.blob(),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name+'-'+file.replaceAll('/','-');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function openLog(name,stage){const response=await artifact(name,stage+'.log'),bytes=new Uint8Array(await response.arrayBuffer());const text=new TextDecoder(bytes[1]===0||bytes[0]===255&&bytes[1]===254?'utf-16le':'utf-8').decode(bytes);$('log-title').textContent=name+' · '+stageNames[stage];$('log-text').textContent=text;$('log-view').hidden=false;$('log-view').scrollIntoView({behavior:'smooth'});}
function renderLegacy(state){$('legacy-runs').replaceChildren();const held=(state.gamma?.jobs||[]).filter(j=>j.blocks_new_work===true);$('legacy-notice').hidden=!held.length;if(held.length){$('legacy-notice').textContent=held.some(j=>j.can_verify)?'Before starting another calculation, choose Verify saved completion in Previous saved jobs and recovery. This reads existing results only.':'Saved Gamma work needs verification or inspection before a new calculation. Verify saved completion is currently unavailable because its activity or uncertainty is unresolved, or its terminal files are incomplete. Review the recorded error below.';}for(const job of state.gamma?.jobs||[]){const row=node('div',undefined,'run');row.append(node('strong','Saved gamma · '+job.label),node('p',job.status));if(job.error)row.append(node('p',job.error.message,'muted'));if(job.can_verify)row.append(action('Verify saved completion',()=>api('/api/gamma-verify',{job_id:job.id})));else if(job.blocks_new_work===true)row.append(node('p','Verify saved completion reads terminal results only. It stays unavailable while this saved job’s activity, uncertainty or incomplete output is unresolved.','muted'));$('legacy-runs').append(row);}for(const job of state.jobs||[]){const row=node('div',undefined,'run');row.append(node('strong','Saved native example · '+job.name),node('p',job.status+' · retained history'));$('legacy-runs').append(row);}}
function renderJobs(state){
  active=state.busy;
  const opened=new Set([...$('runs').querySelectorAll?.('details[open]')||[]].map(n=>n.dataset.run));
  $('runs').replaceChildren();if(!state.jobs.length)$('runs').textContent='No runs created in this application.';
  for(const job of [...state.jobs].reverse()){
    const card=node('div',undefined,'run');
    card.append(node('strong',job.name+' · '+job.selection.detector),node('p',sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' primaries · '+(stateNames[job.status]||job.status)));
    if(job.error)card.append(node('p',job.error,'error'));
    card.append(action('Show stages',()=>showRun(job)));
    if(['running','stop_requested'].includes(job.status))card.append(action('Stop after current stage',()=>api('/api/workflow/stop',{name:job.name})));
    if(job.status==='stopped')card.append(action('Resume saved settings',()=>api('/api/workflow/resume',{name:job.name})));
    if(['completed','completed_with_native_failures'].includes(job.status))card.append(action('Explore events',()=>openResult(job)),action('Download settings',()=>download(job.name,'resolved-config.json')),action('Download run receipt',()=>download(job.name,'run.json')));
    if(job.status==='dispatch_uncertain')card.append(action('Verify existing completion',()=>api('/api/workflow/verify',{name:job.name})),action('Inspect denied launch',()=>api('/api/workflow/inspect-failure',{name:job.name})));
    if(job.can_finalize_results)card.append(node('p','The response worker finished. Finalize saved results verifies existing science, preserves the original failed receipt and creates the results page. No simulation is repeated.','muted'),action('Finalize saved results',async()=>{const next=await api('/api/workflow/finalize-results',{name:job.name});showRun(next);notice('Saved results verified and finalized. Original science and compute timings were preserved.');}));
    if(job.can_continue_prefix){
      const label=node('label','New run name for '+job.name),input=node('input');
      input.id='continue-name-'+job.id;label.htmlFor=input.id;input.maxLength=48;
      input.value=continuationNames.get(job.name)||job.name+'-continued';
      input.addEventListener('input',()=>continuationNames.set(job.name,input.value));label.append(input);
      card.append(node('p','Keep this run’s detector, source and electronics settings. Reuse verified transport; calculate charge and readout in a new run.','muted'),label,
        action('Continue from verified transport',async()=>{const next=await api('/api/workflow/continue-prefix',{name:job.name,new_name:input.value});showRun(next);notice('Reserved '+next.name+'. Verified transport is reused; response and results will run.');}));
    }
    const details=node('details'),summary=node('summary','Stage receipts and logs');details.dataset.run=job.name;details.open=opened.has(job.name);details.append(summary);
    for(const [stage,r]of Object.entries(job.stages)){details.append(node('p',stageNames[stage]+' · '+r.status));if(stage!=='results')details.append(action('Open '+stage+' log',()=>openLog(job.name,stage)));}
    details.append(node('pre',JSON.stringify(job.stages,null,2)));card.append(details);$('runs').append(card);
    if(selectedJob===job.name)showRun(job);
  }
  controls();
}
async function poll(){try{const [state,legacy]=await Promise.all([api('/api/workflow/state'),api('/api/state')]);renderJobs(state);renderLegacy(legacy);}catch(e){notice(e.message,true);}}
$('open-saved-gamma').onclick=async()=>{const button=$('open-saved-gamma');button.disabled=true;try{const r=await api('/api/open-saved-gamma',{});if(r.science_calls!==0||r.census?.radiation_primaries!==40||![6,40].includes(r.census.selected_primaries)||r.census.unprocessed_primaries!==40-r.census.selected_primaries)throw Error('Unexpected saved gamma census.');$('saved-gamma-status').textContent='Checked '+r.census.selected_primaries+' responses across all40 original primaries; browser open requested. No calculation ran.';}catch(e){$('saved-gamma-status').textContent=e.message;}finally{button.disabled=false;}};
async function openResult(job){const prior=result?.job.name===job.name&&result?.job.configuration_sha256===job.configuration_sha256?{id:Number($('event').value),groupIndex:Number($('group').value)}:null;showRun(job);const generation=++resultGeneration;plotGeneration++;result=null;$('plots').replaceChildren();$('result').hidden=true;try{const responses=await Promise.all([artifact(job.name,'response/run.json'),artifact(job.name,'COMPLETE.json')]);const [report,complete]=await Promise.all(responses.map(r=>r.json()));if(generation!==resultGeneration||selectedJob!==job.name)return;const summaryHash=complete.artifacts?.['response/summary.html']?.sha256;if(complete.configuration_sha256!==job.configuration_sha256||!summaryHash||report.artifacts?.['summary.html']!==summaryHash||report.source_id!==undefined&&report.source_id!==job.selection.source)throw Error('Saved result and selected run identities differ.');let records=[],traces=[];if(report.cases){records=report.cases;}else{const files=await Promise.all([artifact(job.name,'response/scalars.jsonl'),artifact(job.name,'response/traces.jsonl')]);const texts=await Promise.all(files.map(r=>r.text()));if(generation!==resultGeneration||selectedJob!==job.name)return;[records,traces]=texts.map(s=>s.trim().split('\n').filter(Boolean).map(JSON.parse));}if(generation!==resultGeneration||selectedJob!==job.name)return;result={job,report,records,traces,summaryHash};savedArtifacts(job,complete);$('result').hidden=false;$('result-heading').textContent=job.name+' · '+job.selection.detector+' · '+sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' original primaries';const ids=[...new Set(records.map(r=>r.initial_primary_id??r.event_id))];options('event',ids.map(id=>({id:String(id),label:String(id)})));const choice=prior&&ids.includes(prior.id)?prior:firstSavedWaveform(records,traces);if(choice)$('event').value=String(choice.id);showEvent(choice?.groupIndex);$('result').scrollIntoView({behavior:'smooth'});}catch(e){if(generation===resultGeneration&&selectedJob===job.name)throw e;}}
function savedArtifacts(job,complete){const list=$('saved-artifacts');list.replaceChildren();const groups=[
  ['Configuration and completion',['resolved-config.json','run.json','COMPLETE.json','decay-request.json']],
  ['World, source and radiation',['transport/prepared.json','transport/geometry-report.json','transport/run.json','transport/truth.lh5']],
  ['Original initial-primary ledger',['transport/stream/manifest.json',...Object.keys(complete.artifacts).filter(f=>/^transport\/stream\/[^/]+\.jsonl$/.test(f))]],
  ['Native signals and readout',['response/run.json','response/truth.jsonl','response/scalars.jsonl','response/traces.jsonl']],
  ['Independent calibration',['electronics/profile.json','response/readout-config.json','response/calibration.json','response/negative-injection.json','response/summary.html']]
];for(const [title,files]of groups){const present=files.filter(f=>f==='COMPLETE.json'||complete.artifacts[f]);if(!present.length)continue;const row=node('div');row.append(node('strong',title));for(const file of present){const stamp=complete.artifacts[file];row.append(action('Download '+file,()=>download(job.name,file)),node('small',stamp?stamp.bytes+' bytes · SHA256 '+stamp.sha256:'Completion inventory · binds every saved artifact'));}list.append(row);}}
function primaryRecords(records,id){return records.filter(r=>(r.initial_primary_id??r.event_id)===id);}
function firstSavedWaveform(records,traces){const r=records.find(r=>(r.truth_ge_edep_keV??r.deposited_energy_keV)>0&&r.readout&&(r.readout.trace||traces.some(t=>t.event_id===r.event_id&&t.group_id===r.group_id)));if(!r)return null;const id=r.initial_primary_id??r.event_id;return {id,groupIndex:primaryRecords(records,id).indexOf(r)};}
function metricValue(value){return value==null?'Unavailable':String(value);}
function showEvent(groupIndex=0){const id=Number($('event').value),rs=primaryRecords(result.records,id);$('event-record').textContent=JSON.stringify(rs,null,2);options('group',rs.map((r,index)=>({id:String(index),label:r.record_kind==='pulse'?'Pulse group '+r.group_id+' · origin '+r.origin_time_ns+' ns':r.record_kind==='decay'||r.record_kind==='primary'?'Primary summary':r.zero_ge?'Known zero input':'Gamma response · group 0'})));if(Number.isInteger(groupIndex)&&groupIndex>=0&&groupIndex<rs.length)$('group').value=String(groupIndex);showGroup();}
function savedGroup(r){if(r.record_kind==='pulse'&&Number.isInteger(r.group_id))return {id:r.group_id};if(!r.record_kind&&Number.isInteger(r.initial_primary_id)&&typeof r.zero_ge==='boolean')return {id:r.zero_ge?null:0};return null;}
function safeSvg(fragment){if(typeof fragment!=='string'||fragment.includes('<!')||fragment.includes('<?'))throw Error('Unsupported saved SVG.');const parsed=new DOMParser().parseFromString(fragment,'image/svg+xml');if(parsed.doctype||parsed.getElementsByTagName('parsererror').length||parsed.documentElement.localName!=='svg')throw Error('Malformed saved SVG.');const ns='http://www.w3.org/2000/svg',allowed={svg:['role','aria-label','viewbox','xmlns'],path:['d','fill','stroke'],polyline:['points','fill','stroke','stroke-width'],text:['x','y']};function copy(element){const tag=element.localName;if(element.prefix||!allowed[tag]||element.namespaceURI&&element.namespaceURI!==ns)throw Error('Unsupported saved SVG element.');const output=document.createElementNS(ns,tag);for(const a of element.attributes){if(a.prefix||!allowed[tag].includes(a.name.toLowerCase())||a.name==='xmlns'&&a.value!==ns)throw Error('Unsupported saved SVG attribute.');output.setAttribute(a.name,a.value);}for(const child of element.childNodes){if(child.nodeType===1)output.append(copy(child));else if(child.nodeType===3)output.append(document.createTextNode(child.nodeValue));else throw Error('Unsupported saved SVG node.');}return output;}return copy(parsed.documentElement);}
async function loadPlots(context,id,group,generation){
  try{
    const reply=await api('/api/workflow-file/focus?'+new URLSearchParams({name:context.job.name,primary:String(id),group:group===null?'none':String(group)}));
    if(generation!==plotGeneration||context!==result||selectedJob!==context.job.name)return;
    if(reply.kind!=='saved_focus_projection_v1'||reply.name!==context.job.name||reply.configuration_sha256!==context.job.configuration_sha256||reply.primary_id!==id||reply.group_id!==group||reply.summary_sha256!==context.summaryHash||reply.panels?.length!==4)throw Error('Saved waveform and current selection identities differ.');
    const record=primaryRecords(context.records,id).find(r=>savedGroup(r)?.id===group);
    if(record?.record_kind==='pulse'&&(reply.global_decay_id!==record.global_decay_id||reply.origin_time_ns!==record.origin_time_ns))throw Error('Saved pulse-group origin differs.');
    const hashes=[reply.sidecar_manifest_sha256,reply.sidecar_data_sha256];
    if(!hashes.every(h=>h===null)&&!hashes.every(h=>typeof h==='string'&&/^[0-9a-f]{64}$/.test(h)))throw Error('Incomplete display derivative binding.');
    const peak=reply.panels[3].peak;if(!peak||!Object.is(peak.t,record.readout.peak_time_ns)||!Object.is(peak.v,record.readout.peak_V))throw Error('Original sampled peak changed.');
    SavedFocusPlots.draw($('plots'),reply.panels,reply.clock);
    const original=node('button','Download original saved plots');original.onclick=()=>download(context.job.name,'response/summary.html').catch(e=>notice(e.message,true));
    $('plots').append(original,node('p',reply.notes.join(' '),'muted'),node('small','Original artifact SHA256 · '+reply.summary_sha256+(hashes[0]?' · display derivative '+hashes[0]:'')));
  }catch(e){if(generation===plotGeneration&&context===result)$('plots').replaceChildren(node('p',e.message,'error'));}
}
function showGroup(){const generation=++plotGeneration,id=Number($('event').value),rs=primaryRecords(result.records,id),r=rs[Number($('group').value)],primary=rs.find(r=>['decay','primary'].includes(r.record_kind));$('event-identity').textContent='Initial primary '+id+(r.record_kind==='pulse'?' · pulse group '+r.group_id+' · origin '+r.origin_time_ns+' ns':primary?' · primary summary · '+primary.pulse_count+' pulse groups':r.zero_ge?' · known zero input':' · gamma response group 0');$('result-data').replaceChildren();const edep=r.truth_ge_edep_keV??r.deposited_energy_keV,charge=r.final_induced_keV??(r.zero_deposit?0:null),rec=r.readout?.reconstructed_energy_keV,metrics=node('div',undefined,'metrics');for(const [label,value]of [['Truth Edep · keV',edep],['Induced equivalent · keV',charge],['Reconstructed energy · keV',rec]]){const span=node('span',label);span.append(node('strong',metricValue(value)));metrics.append(span);} $('result-data').append(metrics,node('p',r.status||r.rejection_reason||(r.zero_deposit?'True zero deposition · no pulse group':r.record_kind==='pulse'?'Recorded pulse group':'Recorded primary')));const group=savedGroup(r),hasTrace=group&&(r.readout?.trace||result.traces.some(t=>t.event_id===id&&t.group_id===group.id));$('plots').replaceChildren(node('p',hasTrace?'Loading original saved waveforms…':r.zero_deposit?'No pulse waveform for this zero-deposit primary.':'No saved waveform for this record. Pulse groups retain their scalar results.','muted'));if(hasTrace)loadPlots(result,id,group.id,generation);}
$('event').onchange=()=>showEvent();
$('group').onchange=showGroup;
$('setup').onclick=async()=>{try{const r=await api('/api/workflow/setup');$('setup-notice').textContent=r.checks.map(c=>(c.available?'✓ ':'Missing: ')+c.label).join(' · ')+' '+r.note;}catch(e){$('setup-notice').textContent=e.message;}};
$('check').onclick=async()=>{if(busy||active||!executableSelection())return;const submitted=config(),serialized=JSON.stringify(submitted),version=selectionVersion;busy=true;checked=null;controls();try{const reply=await api('/api/workflow/check',{config:submitted});if(version!==selectionVersion||JSON.stringify(config())!==serialized){notice('Selection changed while Check was pending. Check the current setup.');return;}checked=reply;$('checked-plan').textContent=JSON.stringify(checked.resolved,null,2);notice('Configuration checked. Run starts new radiation and follows the selected settings.');}catch(e){if(version===selectionVersion){checked=null;notice(e.message,true);}}finally{busy=false;controls();}};
$('start').onclick=async()=>{if(busy||active||!checked||!executableSelection())return;busy=true;controls();try{const job=await api('/api/workflow/start',{check_id:checked.check_id});showRun(job);checked=null;notice('Run reserved: '+job.name+'. Stages will appear as the backend observes them.');await poll();}catch(e){checked=null;notice(e.message,true);}finally{busy=false;controls();}};
$('save').onclick=()=>{if(busy||active||!executableSelection())return;const blob=new Blob([JSON.stringify(config(),null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='gesignal-configuration.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function importedConfig(c){const fields=['name','cryostat','detector','source','pose','primary_count','seed','threads','electronics'];if(!c||Array.isArray(c)||Object.keys(c).sort().join()!=fields.sort().join()||!c.electronics||Object.keys(c.electronics).sort().join()!=[...catalog.electronics_keys].sort().join())throw Error('Configuration fields do not match this application.');const source=catalog.sources.find(s=>s.id===c.source),detector=catalog.detectors.find(d=>d.id===c.detector);if(!source||source.available===false||!catalog.cryostats.some(x=>x.id===c.cryostat&&x.available)||!detector?.available||detector.sources&&!detector.sources.includes(c.source)||source.pose!==c.pose||!source.counts.includes(c.primary_count)||![1,2].includes(c.threads)||!Number.isInteger(c.seed)||c.seed<1||c.seed>2147483646||typeof c.name!=='string'||(source.fixed_seed!=null&&c.seed!==source.fixed_seed))throw Error('The imported setup is unavailable. No selection was replaced.');for(const key of catalog.electronics_keys){const value=c.electronics[key];if(key==='peak_policy'?typeof value!=='string':key.startsWith('peak_gate_')?value!==null&&(typeof value!=='number'||!Number.isFinite(value)):typeof value!=='number'||!Number.isFinite(value))throw Error('Imported electronics values have invalid types.');}if((c.electronics.peak_gate_start_ns===null)!==(c.electronics.peak_gate_end_ns===null))throw Error('A peak gate requires both boundaries.');return c;}
$('load').onclick=()=>{if(!busy&&!active)$('import').click();};$('import').onchange=async()=>{const generation=++importGeneration,version=selectionVersion;try{if(busy||active)throw Error('Wait for the current action before loading a configuration.');const f=$('import').files[0];if(!f||f.size>65536)throw Error('Choose a configuration JSON under 64 KiB.');const c=importedConfig(JSON.parse(await f.text()));if(generation!==importGeneration||version!==selectionVersion||busy||active)throw Error('Selection or activity changed while loading. Choose the configuration file again.');for(const id of ['name','cryostat','detector','source','threads'])$(id).value=c[id];detectorChanged();$('seed').value=c.seed;$('count').value=String(c.primary_count);$('pose').value=c.pose;for(const key of catalog.electronics_keys)$('setting-'+key).value=c.electronics[key]??'';$('use-peak-gate').checked=c.electronics.peak_gate_start_ns!==null;gateFields();invalidate();notice('Configuration loaded. Check plan validates the admitted setup.');}catch(e){if(generation===importGeneration)notice(e.message,true);}finally{if(generation===importGeneration)$('import').value='';}};
(async()=>{try{catalog=await api('/api/workflow/catalog');options('cryostat',catalog.cryostats);options('detector',catalog.detectors,true);$('detector').value='AK02';electronics();$('numerics').textContent=catalog.numerics;$('setup-limit').textContent=catalog.setup_limit||'';detectorChanged();stageList();for(const id of ['cryostat','pose','count','seed','threads','name'])$(id).addEventListener('input',invalidate);$('detector').onchange=detectorChanged;$('source').onchange=sourceChanged;await poll();setInterval(poll,2500);}catch(e){notice(e.message,true);$('check').disabled=true;}})();
