'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('ge-control-token')||'';
if(token)sessionStorage.setItem('ge-control-token',token);history.replaceState(null,'',location.pathname);
let catalog=null,checked=null,busy=false,active=false,selectedJob=null,selectedRun=null,result=null,selectionVersion=0,resultGeneration=0,plotGeneration=0;
let modelPreviewGeneration=0,modelPreviewUrl=null,importGeneration=0,pageGeneration=0,pollGeneration=0;
const continuationNames=new Map();
const stageNames={native_preparation:'Fields and injection calibration',geometry:'Geometry and source',radiation:'Radiation transport',event_ledger:'Event ledger',response:'Fields, charge, calibration and readout',results:'Verified results'};
const stateNames={dispatch_uncertain:'Inspection required',running:'Running',stop_requested:'Stop requested',stopped:'Stopped at stage boundary',completed:'Completed',completed_with_native_failures:'Completed with native failures',inspected_failure:'Inspected denied launch · preserved',verified_transport:'Verified transport · original failure preserved'};
const labels={shaping_tau_us:['Shaping time','µs'],gain:['Shaper gain','V/V'],threshold_V:['Peak threshold','V'],adc_bits:['Peak ADC bits','bits'],adc_full_scale_V:['Peak ADC full scale','V'],feedback_capacitance_pF:['Feedback capacitance','pF'],feedback_tau_us:['Feedback decay','µs'],pole_zero_tau_us:['Pole-zero time','µs'],peak_policy:['Peak policy',''],peak_gate_start_ns:['Peak gate start','ns; blank = none'],peak_gate_end_ns:['Peak gate end','ns; blank = none']};
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'X-Control-Token':token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),cache:'no-store'});const v=await r.json();if(!r.ok)throw Error(v.error||'Local action failed.');return v;}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className='notice '+(error?'error':'okay');}
function options(id,items,inspection=false){const s=$(id);s.replaceChildren();for(const item of items){const suffix=inspection?(item.available?' · Compute supported':item.block_code==='cryostat_size'?' · Needs larger cryostat':' · View only'):item.available===false?' · '+item.reason:'';const o=node('option',item.label+suffix);o.value=item.id;o.disabled=!inspection&&item.available===false;s.append(o);}}
function detectorItems(){return [...catalog.detectors.filter(d=>d.available===true),...catalog.detectors.filter(d=>d.available!==true)];}
function sharedModelSelection(){return currentDetector()?.workflow_kind==='local_catalog_workflow_v1';}
function showModelRequirements(d){const list=$('model-parameters');list.replaceChildren();if(!d.parameter_summary?.length&&d.operating_label)list.append(node('li',d.operating_label));for(const p of d.parameter_summary||[]){const row=node('li',p.label+': '+String(p.value)+(p.unit?' '+p.unit:''));list.append(row);}const checks=$('model-checks');checks.replaceChildren();for(const c of d.checks||[]){checks.append(node('li',c.label+' · '+c.status+(c.detail?' · '+c.detail:'')));}$('model-requirements').hidden=!list.children.length&&!checks.children.length;}
function currentDetector(){return catalog?.detectors.find(d=>d.id===$('detector').value);}
function currentSource(){return catalog?.sources.find(s=>s.id===$('source').value);}
function executableSelection(){const d=currentDetector();return d?.available===true&&currentSource()?.available!==false&&d.sources.includes($('source').value)&&catalog.cryostats.some(c=>c.id===$('cryostat').value&&c.available===true);}
function batchSelection(){return currentSource()?.id!=='mono_gamma_662_axis_v1';}
function exactInteger(text,label,positive=true){if(typeof text!=='string'||! /^[0-9]+$/.test(text))throw Error(label+' must be a decimal integer.');const n=Number(text);if(!Number.isSafeInteger(n)||n<(positive?1:0))throw Error(label+' is outside the exact safe-integer range.');return n;}
function batchRequest(selection){return {kind:'local_scenario_batch_request_v2',schema_version:2,selection};}
function config(){const electronics={};for(const key of catalog.electronics_keys){const value=$('setting-'+key).value;electronics[key]=key.startsWith('peak_gate_')&&!$('use-peak-gate').checked?null:key==='peak_policy'?value:value===''?null:Number(value);}return {name:$('name').value,cryostat:$('cryostat').value,detector:$('detector').value,source:$('source').value,pose:$('pose').value,primary_count:exactInteger($('count').value,'Initial primaries'),seed:Number($('seed').value),threads:Number($('threads').value),electronics};}
function invalidate(){selectionVersion++;checked=null;$('checked-plan').textContent=executableSelection()?'Selection changed. Check the new plan.':'No run plan for this setup. '+(currentDetector()?.reason||'Read the selected model’s configuration requirements.');showSelection();controls();}
function controls(){const runnable=executableSelection();for(const id of ['check','save'])$(id).disabled=busy||active||!runnable;$('load').disabled=busy||active;$('start').disabled=busy||active||!runnable||!checked;
for(const id of ['cryostat','source','pose','count','threads','name','use-peak-gate'])$(id).disabled=!runnable;$('seed').disabled=!runnable||!batchSelection()&&currentSource()?.fixed_seed!=null;for(const key of catalog?.electronics_keys||[])$('setting-'+key).disabled=!runnable||key.startsWith('peak_gate_')&&!$('use-peak-gate').checked;}
function sourceLabel(id){return catalog?.sources.find(s=>s.id===id)?.label||id;}
function detectorChanged(){const previous=$('source').value,d=currentDetector(),sources=catalog.sources.filter(s=>d.sources.includes(s.id));options('source',sources);$('source').value=sources.some(s=>s.id===previous)?previous:sources[0]?.id||'';$('operating-details').textContent=d.operating_label||'';showModel(d);sourceChanged();}
function showModel(d){const m=d.model||{},count=catalog.detectors.filter(x=>x.available===true).length;
$('catalog-counts').textContent=catalog.detectors.length+' catalog models can be inspected; '+count+' have supported local computation connectors. The public website shows saved results.';
$('model-capability').textContent=d.available?(sharedModelSelection()?'Available in the current cryostat. Check plan before Run.':'Computation supported for the listed sources. Check plan before Run.'):'View only · '+(d.reason||'No executable configuration is available for this setup.');$('model-capability-details').textContent=d.reason||d.operating_label||'';
$('model-title').textContent=d.id;$('model-summary').textContent=[d.type_label,m.group,m.status,m.coordinate_system?m.coordinate_system+' coordinates':''].filter(Boolean).join(' · ');
$('model-contact-summary').textContent=(m.contacts||[]).length+' contacts · catalog readout contact '+(m.readout_contact_id??'unavailable');$('model-contact-list').open=(m.contacts||[]).length<=8;$('model-contacts').replaceChildren();$('model-contacts').tabIndex=(m.contacts||[]).length>8?0:-1;for(const c of m.contacts||[])$('model-contacts').append(node('li','Contact '+c.id+' · '+c.name+' · '+(c.potential_V>0?'+':'')+c.potential_V+' V'+(c.id===m.readout_contact_id?' · catalog readout':'')));
$('model-assumptions').textContent=(m.assumptions||[]).join(' ');$('model-variant').textContent=d.id==='GeRC02'?'Preview: frozen catalog Ge30min base. Computation: separate Li50min variant at 553.15 K; stored 78 K, runtime 77 K; fresh fields.':'';
showModelRequirements(d);$('model-identity').textContent=JSON.stringify(m,null,2);$('model-view').href=d.geometry_url||'';$('model-view').hidden=!d.geometry_url;loadModelPreview(d);}
async function loadModelPreview(d){const generation=++modelPreviewGeneration;if(modelPreviewUrl){URL.revokeObjectURL(modelPreviewUrl);modelPreviewUrl=null;}$('model-preview-box').hidden=true;$('model-preview').removeAttribute('src');$('model-preview-status').textContent='Loading saved catalog geometry…';
try{const r=await fetch('/api/model-preview?'+new URLSearchParams({model:d.id}),{headers:{'X-Control-Token':token},cache:'no-store'});if(!r.ok)throw Error('Saved preview unavailable here. Use Open saved rotatable geometry on the public website.');const blob=await r.blob();if(generation!==modelPreviewGeneration||currentDetector()?.id!==d.id)return;modelPreviewUrl=URL.createObjectURL(blob);$('model-preview').src=modelPreviewUrl;$('model-preview').alt=d.id+' saved catalog geometry';$('model-preview-box').hidden=false;$('model-preview-status').textContent='Saved geometry · no calculation ran.';}catch(e){if(generation===modelPreviewGeneration)$('model-preview-status').textContent=e.message;}}
function showSelection(){if(!catalog)return;$('setup-preview').textContent=executableSelection()?'Current setup · '+$('detector').value+' · '+sourceLabel($('source').value)+' · '+$('count').value+' initial primaries · '+$('threads').value+' Julia threads':'Inspecting catalog model · '+$('detector').value+' · view only; no source or computation selected';}
function showRun(job){const changed=selectedJob!==job.name||selectedRun?.configuration_sha256!==job.configuration_sha256;if(changed){resultGeneration++;plotGeneration++;result=null;$('result').hidden=true;$('plots').replaceChildren();}selectedJob=job.name;selectedRun=job;$('selected').textContent='Selected run · '+job.name+' · '+job.selection.detector+' · '+sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' initial primaries';$('run-plan').textContent=JSON.stringify({configuration_sha256:job.configuration_sha256,selection:job.selection},null,2);stageList(job.stages,job.execution_contract==='serial_batches_v3');responseProgress(job);batchProgress(job);}
function sourceChanged(){const s=currentSource();if(!s){options('pose',[]);if(!$('count').value)$('count').value='500';$('source-details').textContent='A source cannot be selected until this detector has a checked computation connector.';$('source-identity').textContent='';invalidate();return;}options('pose',[{id:s.pose,label:s.pose_label||s.pose}]);const batching=batchSelection();$('count').readOnly=!batching;if(!batching)$('count').value=String(s.counts[0]);else if(!$('count').value)$('count').value='500';$('count-limit').textContent=batching?'Enter an exact positive integer (1..9007199254740991). Serial radiation batches contain at most 10000 initial primaries. Check separately enforces seed capacity; practical runtime and storage are not guaranteed by that numeric limit.':'This gamma connector retains its checked legacy 20-primary example and fixed radiation seed. Arbitrary-count gamma execution is pending.';$('seed').disabled=!batching&&s.fixed_seed!=null;if($('seed').disabled)$('seed').value=String(s.fixed_seed);$('source-details').textContent=[s.details||s.reason,s.count_unit?'Count unit: '+s.count_unit+'.':null,s.position_global_mm?'Position ['+s.position_global_mm.join(', ')+'] mm in the global frame.':null].filter(Boolean).join(' ');$('source-identity').textContent=JSON.stringify({source_id:s.id,count_unit:s.count_unit,position_global_mm:s.position_global_mm,source_contract:s.source_contract,acceptance:s.acceptance},null,2);invalidate();}

function electronics(){for(const key of catalog.electronics_keys){const [name,unit]=labels[key],label=node('label',name+(unit?' · '+unit:''));let input;if(key==='peak_policy'){input=node('select');for(const [value,text] of [['signed_input_positive_peak','Signed input, positive peak'],['legacy_reject_negative_input','Reject negative input']]){const o=node('option',text);o.value=value;input.append(o);}}else{input=node('input');input.type='number';input.step=key==='adc_bits'?'1':'any';}input.id='setting-'+key;label.htmlFor=input.id;input.value=catalog.electronics_defaults[key]??'';input.addEventListener('input',invalidate);label.append(input);$('electronics').append(label);}gateFields();}
function gateFields(){for(const key of ['peak_gate_start_ns','peak_gate_end_ns'])$('setting-'+key).disabled=!$('use-peak-gate').checked;}
$('use-peak-gate').onchange=()=>{gateFields();invalidate();};
function stageList(stages={},batched=false){$('pipeline').replaceChildren();const entries=batched?Object.keys(stages).map(key=>[key,stageNames[key]||key.replaceAll('_',' ')]):Object.entries(stageNames).filter(([key])=>key!=='native_preparation');for(const [key,title] of entries){const r=stages[key],row=node('div',undefined,'stage '+(r?.status||''));row.append(node('span',undefined,'dot'));const titleBox=node('div',title,'stage-title');titleBox.append(node('small',r?.reuse?(typeof r.original_elapsed_seconds==='number'?'Reused · originally '+r.original_elapsed_seconds.toFixed(2)+' s':'Reused · saved artifacts verified; original execution time unavailable'):typeof r?.elapsed_seconds==='number'?r.elapsed_seconds.toFixed(2)+' s observed':r?.status==='completed'?'Completed · saved receipt':'Waiting for execution'));row.append(titleBox,node('span',r?.reuse?'Reused':r?.status==='completed'?'Completed':r?.status?.replaceAll('_',' ')||'Pending','pill'));$('pipeline').append(row);}}
function batchProgress(job){const p=job.batch_progress;$('batch-progress').textContent=job.execution_contract==='serial_batches_v3'?(p?'Completed '+(p.completed_batch_count??0)+'/'+(p.batch_count??job.batching?.batch_count)+' batches · '+(p.completed_primary_count??0)+'/'+job.selection.primary_count+' initial primaries'+(Number.isInteger(p.active_batch_index)?' · active batch '+p.active_batch_index:'')+(p.active_stage?' · '+p.active_stage.replaceAll('_',' '):''):'Checked serial plan · '+job.batching?.batch_count+' batches · '+job.selection.primary_count+' initial primaries · awaiting the first receipt'):'';}
function responseProgress(job){const p=job.response_progress;$('response-progress').textContent=p?'Native stage: '+p.stage.replaceAll('_',' ')+' · '+p.status+(p.expected_primary_count!==null?' · '+p.completed_primary_count+'/'+p.expected_primary_count+' original primaries':'')+' · '+p.elapsed_seconds.toFixed(2)+' s observed':'';}
function action(label,fn){const b=node('button',label);b.onclick=async()=>{b.disabled=true;try{await fn();await poll();}catch(e){notice(e.message,true);}finally{if(b.isConnected)b.disabled=false;}};return b;}
async function artifact(name,file,rawDownload=false){const r=await fetch('/api/workflow-file?'+new URLSearchParams({name,file,...(rawDownload?{download:'1'}:{})}),{headers:{'X-Control-Token':token},cache:'no-store'});if(!r.ok){const e=await r.json();throw Error(e.error||'Artifact unavailable.');}return r;}
async function download(name,file){const r=await artifact(name,file,true),blob=await r.blob(),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name+'-'+file.replaceAll('/','-');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function openLogFile(name,file,label){const response=await artifact(name,file),bytes=new Uint8Array(await response.arrayBuffer());const text=new TextDecoder(bytes[1]===0||bytes[0]===255&&bytes[1]===254?'utf-16le':'utf-8').decode(bytes);$('log-title').textContent=name+' · '+label;$('log-text').textContent=text;$('log-view').hidden=false;$('log-view').scrollIntoView({behavior:'smooth'});}
async function openLog(name,stage){return openLogFile(name,stage+'.log',stageNames[stage]||stage);}
function renderLegacy(state){$('legacy-runs').replaceChildren();const held=(state.gamma?.jobs||[]).filter(j=>j.blocks_new_work===true);$('legacy-notice').hidden=!held.length;if(held.length){$('legacy-notice').textContent=held.some(j=>j.can_verify)?'Before starting another calculation, choose Verify saved completion in Previous saved jobs and recovery. This reads existing results only.':'Saved Gamma work needs verification or inspection before a new calculation. Verify saved completion is currently unavailable because its activity or uncertainty is unresolved, or its terminal files are incomplete. Review the recorded error below.';}for(const job of state.gamma?.jobs||[]){const row=node('div',undefined,'run');row.append(node('strong','Saved gamma · '+job.label),node('p',job.status));if(job.error)row.append(node('p',job.error.message,'muted'));if(job.can_verify)row.append(action('Verify saved completion',()=>api('/api/gamma-verify',{job_id:job.id})));else if(job.blocks_new_work===true)row.append(node('p','Verify saved completion reads terminal results only. It stays unavailable while this saved job’s activity, uncertainty or incomplete output is unresolved.','muted'));$('legacy-runs').append(row);}for(const job of state.jobs||[]){const row=node('div',undefined,'run');row.append(node('strong','Saved native example · '+job.name),node('p',job.status+' · retained history'));$('legacy-runs').append(row);}}
function renderJobs(state){
  active=state.busy;
  const opened=new Set([...$('runs').querySelectorAll?.('details[open]')||[]].map(n=>n.dataset.run));
  $('runs').replaceChildren();if(!state.jobs.length)$('runs').textContent='No runs created in this application.';
  for(const job of [...state.jobs].reverse()){
    const card=node('div',undefined,'run');
    card.append(node('strong',job.name+' · '+job.selection.detector),node('p',sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' primaries · '+(stateNames[job.status]||job.status)));
    if(job.error)card.append(node('p',job.error,'error'));
    card.append(action('Show stages',()=>showRun(job)));
    if(['running','stop_requested'].includes(job.status))card.append(action(job.execution_contract==='serial_batches_v3'?'Stop at next boundary':'Stop after current stage',()=>api('/api/workflow/stop',{name:job.name})));
    if(job.status==='stopped')card.append(action('Resume saved settings',()=>api('/api/workflow/resume',{name:job.name})));
    if(['completed','completed_with_native_failures'].includes(job.status)||job.execution_contract==='serial_batches_v3'&&job.status==='stopped'&&job.batch_progress?.completed_batch_count>0)card.append(action('Explore events',()=>openResult(job)),action('Download settings',()=>download(job.name,'resolved-config.json')),action('Download run receipt',()=>download(job.name,'run.json')));
    if(job.status==='dispatch_uncertain'){card.append(action('Verify existing completion',()=>api('/api/workflow/verify',{name:job.name})));if(job.can_inspect_failure!==false)card.append(action('Inspect denied launch',()=>api('/api/workflow/inspect-failure',{name:job.name})));}
    if(job.can_finalize_results)card.append(node('p','The response worker finished. Finalize saved results verifies existing science, preserves the original failed receipt and creates the results page. No simulation is repeated.','muted'),action('Finalize saved results',async()=>{const next=await api('/api/workflow/finalize-results',{name:job.name});showRun(next);notice('Saved results verified and finalized. Original science and compute timings were preserved.');}));
    if(job.can_continue_prefix){
      const label=node('label','New run name for '+job.name),input=node('input');
      input.id='continue-name-'+job.id;label.htmlFor=input.id;input.maxLength=48;
      input.value=continuationNames.get(job.name)||job.name+'-continued';
      input.addEventListener('input',()=>continuationNames.set(job.name,input.value));label.append(input);
      card.append(node('p','Keep this run’s detector, source and electronics settings. Reuse verified transport; calculate charge and readout in a new run.','muted'),label,
        action('Continue from verified transport',async()=>{const next=await api('/api/workflow/continue-prefix',{name:job.name,new_name:input.value});showRun(next);notice('Reserved '+next.name+'. Verified transport is reused; response and results will run.');}));
    }
    const details=node('details'),summary=node('summary','Stage receipts and logs');details.dataset.run=job.name;details.open=opened.has(job.name);details.append(summary);
    for(const [stage,r]of Object.entries(job.stages)){details.append(node('p',(stageNames[stage]||stage.replaceAll('_',' '))+' · '+r.status));if(stage!=='results'&&job.execution_contract!=='serial_batches_v3')details.append(action('Open '+stage+' log',()=>openLog(job.name,stage)));}for(const log of job.logs||[])details.append(action('Open '+log.label+' log',()=>openLogFile(job.name,log.file,log.label)));if(job.batch_progress)details.append(node('pre',JSON.stringify(job.batch_progress,null,2)));
    details.append(node('pre',JSON.stringify(job.stages,null,2)));card.append(details);$('runs').append(card);
    if(selectedJob===job.name)showRun(job);
  }
  controls();
}
async function poll(){const generation=++pollGeneration;try{const [state,legacy]=await Promise.all([api('/api/workflow/state'),api('/api/state')]);if(generation!==pollGeneration)return;renderJobs(state);renderLegacy(legacy);}catch(e){if(generation===pollGeneration)notice(e.message,true);}}
$('open-saved-gamma').onclick=async()=>{const button=$('open-saved-gamma');button.disabled=true;try{const r=await api('/api/open-saved-gamma',{});if(r.science_calls!==0||r.census?.radiation_primaries!==40||![6,40].includes(r.census.selected_primaries)||r.census.unprocessed_primaries!==40-r.census.selected_primaries)throw Error('Unexpected saved gamma census.');$('saved-gamma-status').textContent='Checked '+r.census.selected_primaries+' responses across all40 original primaries; browser open requested. No calculation ran.';}catch(e){$('saved-gamma-status').textContent=e.message;}finally{button.disabled=false;}};
async function openResult(job){if(job.execution_contract==='serial_batches_v3')return openBatchResult(job);const prior=result?.job.name===job.name&&result?.job.configuration_sha256===job.configuration_sha256?{id:Number($('event').value),groupIndex:Number($('group').value)}:null;showRun(job);const generation=++resultGeneration;plotGeneration++;result=null;$('plots').replaceChildren();$('result').hidden=true;try{const responses=await Promise.all([artifact(job.name,'response/run.json'),artifact(job.name,'COMPLETE.json')]);const [report,complete]=await Promise.all(responses.map(r=>r.json()));if(generation!==resultGeneration||selectedJob!==job.name)return;const summaryHash=complete.artifacts?.['response/summary.html']?.sha256;if(complete.configuration_sha256!==job.configuration_sha256||!summaryHash||report.artifacts?.['summary.html']!==summaryHash||report.source_id!==undefined&&report.source_id!==job.selection.source)throw Error('Saved result and selected run identities differ.');let records=[],traces=[];if(report.cases){records=report.cases;}else{const files=await Promise.all([artifact(job.name,'response/scalars.jsonl'),artifact(job.name,'response/traces.jsonl')]);const texts=await Promise.all(files.map(r=>r.text()));if(generation!==resultGeneration||selectedJob!==job.name)return;[records,traces]=texts.map(s=>s.trim().split('\n').filter(Boolean).map(JSON.parse));}if(generation!==resultGeneration||selectedJob!==job.name)return;result={job,report,records,traces,summaryHash};$('batch-navigation').hidden=true;savedArtifacts(job,complete);$('result').hidden=false;$('result-heading').textContent=job.name+' · '+job.selection.detector+' · '+sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' original primaries';const ids=[...new Set(records.map(r=>r.initial_primary_id??r.event_id))];options('event',ids.map(id=>({id:String(id),label:String(id)})));const choice=prior&&ids.includes(prior.id)?prior:firstSavedWaveform(records,traces);if(choice)$('event').value=String(choice.id);showEvent(choice?.groupIndex);$('result').scrollIntoView({behavior:'smooth'});}catch(e){if(generation===resultGeneration&&selectedJob===job.name)throw e;}}
function savedArtifacts(job,complete){const list=$('saved-artifacts');list.replaceChildren();const groups=[
  ['Configuration and completion',['resolved-config.json','run.json','COMPLETE.json','decay-request.json']],
  ['World, source and radiation',['transport/prepared.json','transport/geometry-report.json','transport/run.json','transport/truth.lh5']],
  ['Original initial-primary ledger',['transport/stream/manifest.json',...Object.keys(complete.artifacts).filter(f=>/^transport\/stream\/[^/]+\.jsonl$/.test(f))]],
  ['Native signals and readout',['response/run.json','response/truth.jsonl','response/scalars.jsonl','response/traces.jsonl']],
  ['Independent calibration',['electronics/profile.json','response/readout-config.json','response/calibration.json','response/negative-injection.json','response/summary.html']]
];for(const [title,files]of groups){const present=files.filter(f=>f==='COMPLETE.json'||complete.artifacts[f]);if(!present.length)continue;const row=node('div');row.append(node('strong',title));for(const file of present){const stamp=complete.artifacts[file];row.append(action('Download '+file,()=>download(job.name,file)),node('small',stamp?stamp.bytes+' bytes · SHA256 '+stamp.sha256:'Completion inventory · binds every saved artifact'));}list.append(row);}}
function flatBatchRecords(page){return page.records.flatMap(item=>[item.primary,...item.pulse_groups].filter(Boolean).map(record=>({...record,global_initial_id:item.global_initial_id,local_initial_id:item.local_initial_id,batch_index:item.batch_index,raw_truth:item.truth})));}
function pageIdentity(reply,job,batch,offset){if(reply.kind!=='local_batch_event_page_v1'||reply.name!==job.name||reply.configuration_sha256!==job.configuration_sha256||reply.batch_index!==batch||reply.offset!==offset||reply.limit!==100||!Array.isArray(reply.records)||reply.records.length>100||!Array.isArray(reply.traces)||typeof reply.batch_sha256!=='string'||! /^[0-9a-f]{64}$/.test(reply.batch_sha256))throw Error('Saved event page and selected run identities differ.');for(const [i,row]of reply.records.entries()){if(row.batch_index!==batch||row.local_initial_id!==offset+i||row.global_initial_id!==reply.batch_offset+row.local_initial_id||!Array.isArray(row.pulse_groups)||!row.primary||!row.truth)throw Error('Incomplete saved primary identity.');}return reply;}
async function openBatchResult(job){const prior=result?.job.name===job.name&&result?.job.configuration_sha256===job.configuration_sha256&&result?.page?{batch:result.page.batch_index,offset:result.page.offset,id:Number($('event').value),groupIndex:Number($('group').value)}:null;showRun(job);resultGeneration++;plotGeneration++;pageGeneration++;result={job,page:null,records:[],traces:[]};$('result').hidden=false;$('batch-navigation').hidden=false;$('result-heading').textContent=job.name+' · '+job.selection.detector+' · '+sourceLabel(job.selection.source)+' · '+job.selection.primary_count+' original primaries';$('batch-index').value=String(prior?.batch??0);$('page-offset').value=String(prior?.offset??0);$('saved-artifacts').replaceChildren();$('plots').replaceChildren();await loadBatchPage(prior);$('result').scrollIntoView({behavior:'smooth'});}
async function loadBatchPage(prior){if(!result||result.job.execution_contract!=='serial_batches_v3')return;const context=result,job=context.job,batch=exactInteger($('batch-index').value,'Saved batch index',false),offset=exactInteger($('page-offset').value,'Local primary ID',false),generation=++pageGeneration,runGeneration=resultGeneration;plotGeneration++;$('plots').replaceChildren();$('page-status').textContent='Checking saved batch '+batch+'…';try{const reply=pageIdentity(await api('/api/workflow/events?'+new URLSearchParams({name:job.name,batch:String(batch),offset:String(offset),limit:'100'})),job,batch,offset);if(generation!==pageGeneration||runGeneration!==resultGeneration||context!==result||selectedJob!==job.name)return;context.page=reply;context.records=flatBatchRecords(reply);context.traces=reply.traces;context.summaryHash=reply.response_summary_sha256;const ids=reply.records.map(r=>r.global_initial_id);options('event',ids.map(id=>({id:String(id),label:String(id)})));$('page-status').textContent='Batch '+batch+' · local IDs '+offset+'…'+(offset+reply.records.length-1)+' · global offset '+reply.batch_offset+' · '+reply.batch_primary_count+' primaries in this batch. Every primary on this page is retained.';$('previous-page').disabled=offset===0;$('next-page').disabled=reply.next_offset===null;const choice=prior&&ids.includes(prior.id)?prior:firstSavedWaveform(context.records,context.traces);if(choice)$('event').value=String(choice.id);if(ids.length)showEvent(choice?.groupIndex);else{$('event-record').textContent='No records on this page.';$('result-data').replaceChildren();}batchArtifacts(job,reply);}catch(e){if(generation===pageGeneration&&context===result){$('page-status').textContent=e.message;throw e;}}}
function batchArtifacts(job,page){const list=$('saved-artifacts');list.replaceChildren();for(const file of ['resolved-config.json','run.json',...(['completed','completed_with_native_failures'].includes(job.status)?['COMPLETE.json']:[])])list.append(action('Download '+file,()=>download(job.name,file)));for(const stamp of page.artifacts||[]){list.append(action('Download '+stamp.file,()=>download(job.name,stamp.file)),node('small',stamp.bytes+' bytes · SHA256 '+stamp.sha256));}list.append(node('small','Sealed batch SHA256 · '+page.batch_sha256+' · full raw ledger and traces remain in this saved batch.'));
}
async function loadBatchPlots(context,id,group,generation){try{const batch=context.page.batch_index,reply=await api('/api/workflow/batch-waveforms?'+new URLSearchParams({name:context.job.name,batch:String(batch),primary:String(id),group:group===null?'none':String(group)}));if(generation!==plotGeneration||context!==result||selectedJob!==context.job.name)return;const original=reply.record,record=primaryRecords(context.records,id).find(r=>savedGroup(r)?.id===group);if(reply.kind!=='local_batch_waveform_v1'||reply.name!==context.job.name||reply.configuration_sha256!==context.job.configuration_sha256||reply.batch_index!==batch||reply.batch_sha256!==context.page.batch_sha256||reply.response_summary_sha256!==context.summaryHash||recordPrimary(original)!==id||original.group_id!==group||original.origin_time_ns!==record?.origin_time_ns||!record?.readout)throw Error('Saved batch waveform and current selection identities differ.');const trace=original.trace,rd=record.readout,charge=reply.charge_input,peak={t:rd.peak_time_ns,v:rd.peak_V};if(!charge||!Array.isArray(charge.time_since_origin_ns)||!Array.isArray(charge.induced_equivalent_energy_keV))throw Error('Exact saved charge samples are unavailable.');const t=charge.time_since_origin_ns,q=charge.induced_equivalent_energy_keV,end=Math.min(rd.readout_end_ns,SavedFocusPlots.focusEnd(t,q));const panels=[{title:'Signed native charge · induced equivalent keV',time_ns:t,values:q,full_end_ns:t.at(-1),focus_end_ns:Math.min(t.at(-1),end),note:'Every saved signed native charge sample is retained. The camera focus does not prove complete collection; endpoint and cap flags remain.'},{title:'Original-bin current · nA',time_ns:trace.time_ns,values:trace.raw_native_current_nA||trace.current_nA,bin_start_ns:trace.current_bin_start_ns,bin_end_ns:trace.current_bin_end_ns,full_end_ns:rd.readout_end_ns,focus_end_ns:end,note:'Original (start, end] bins and omitted-bin gaps remain. Display lines are not an integration rule.'},{title:'Analog preamp · V',time_ns:trace.time_ns,values:trace.preamp_V,full_end_ns:rd.readout_end_ns,focus_end_ns:end,note:'Original retained samples; omitted analog samples remain unavailable.'},{title:'Analog shaper · V',time_ns:trace.time_ns,values:trace.shaped_V,full_end_ns:rd.readout_end_ns,focus_end_ns:SavedFocusPlots.shaperEnd(trace.time_ns,trace.shaped_V,peak,rd.readout_end_ns),peak,note:'Gold marker is the exact saved sampled peak. ADC, reconstructed energy and flags remain unchanged.'}];SavedFocusPlots.draw($('plots'),panels,'Time since pulse-group origin · ns');$('plots').append(node('small','Sealed batch SHA256 · '+reply.batch_sha256));}catch(e){if(generation===plotGeneration&&context===result)$('plots').replaceChildren(node('p',e.message,'error'));}}
$('load-page').onclick=()=>loadBatchPage().catch(e=>notice(e.message,true));
$('previous-page').onclick=()=>{if(!result?.page)return;$('page-offset').value=String(Math.max(0,result.page.offset-100));loadBatchPage().catch(e=>notice(e.message,true));};
$('next-page').onclick=()=>{if(result?.page?.next_offset==null)return;$('page-offset').value=String(result.page.next_offset);loadBatchPage().catch(e=>notice(e.message,true));};
function recordPrimary(r){return r.global_initial_id??r.initial_primary_id??r.event_id;}
function primaryRecords(records,id){return records.filter(r=>recordPrimary(r)===id);}
function firstSavedWaveform(records,traces){const r=records.find(r=>(r.truth_ge_edep_keV??r.deposited_energy_keV)>0&&r.readout&&(r.readout.trace||traces.some(t=>recordPrimary(t)===recordPrimary(r)&&t.group_id===r.group_id)));if(!r)return null;const id=recordPrimary(r);return {id,groupIndex:primaryRecords(records,id).indexOf(r)};}
function metricValue(value){return value==null?'Unavailable':String(value);}
function showEvent(groupIndex=0){const id=Number($('event').value),rs=primaryRecords(result.records,id);$('event-record').textContent=JSON.stringify(rs,null,2);options('group',rs.map((r,index)=>({id:String(index),label:r.record_kind==='pulse'?'Pulse group '+r.group_id+' · origin '+r.origin_time_ns+' ns':r.record_kind==='decay'||r.record_kind==='primary'?'Primary summary':r.zero_ge?'Known zero input':'Gamma response · group 0'})));if(Number.isInteger(groupIndex)&&groupIndex>=0&&groupIndex<rs.length)$('group').value=String(groupIndex);showGroup();}
function savedGroup(r){if(r.record_kind==='pulse'&&Number.isInteger(r.group_id))return {id:r.group_id};if(!r.record_kind&&Number.isInteger(r.initial_primary_id)&&typeof r.zero_ge==='boolean')return {id:r.zero_ge?null:0};return null;}
function safeSvg(fragment){if(typeof fragment!=='string'||fragment.includes('<!')||fragment.includes('<?'))throw Error('Unsupported saved SVG.');const parsed=new DOMParser().parseFromString(fragment,'image/svg+xml');if(parsed.doctype||parsed.getElementsByTagName('parsererror').length||parsed.documentElement.localName!=='svg')throw Error('Malformed saved SVG.');const ns='http://www.w3.org/2000/svg',allowed={svg:['role','aria-label','viewbox','xmlns'],path:['d','fill','stroke'],polyline:['points','fill','stroke','stroke-width'],text:['x','y']};function copy(element){const tag=element.localName;if(element.prefix||!allowed[tag]||element.namespaceURI&&element.namespaceURI!==ns)throw Error('Unsupported saved SVG element.');const output=document.createElementNS(ns,tag);for(const a of element.attributes){if(a.prefix||!allowed[tag].includes(a.name.toLowerCase())||a.name==='xmlns'&&a.value!==ns)throw Error('Unsupported saved SVG attribute.');output.setAttribute(a.name,a.value);}for(const child of element.childNodes){if(child.nodeType===1)output.append(copy(child));else if(child.nodeType===3)output.append(document.createTextNode(child.nodeValue));else throw Error('Unsupported saved SVG node.');}return output;}return copy(parsed.documentElement);}
async function loadPlots(context,id,group,generation){
  if(context.page)return loadBatchPlots(context,id,group,generation);
  try{
    const reply=await api('/api/workflow-file/focus?'+new URLSearchParams({name:context.job.name,primary:String(id),group:group===null?'none':String(group)}));
    if(generation!==plotGeneration||context!==result||selectedJob!==context.job.name)return;
    if(reply.kind!=='saved_focus_projection_v1'||reply.name!==context.job.name||reply.configuration_sha256!==context.job.configuration_sha256||reply.primary_id!==id||reply.group_id!==group||reply.summary_sha256!==context.summaryHash||reply.panels?.length!==4)throw Error('Saved waveform and current selection identities differ.');
    const record=primaryRecords(context.records,id).find(r=>savedGroup(r)?.id===group);
    if(record?.record_kind==='pulse'&&(reply.global_decay_id!==record.global_decay_id||reply.origin_time_ns!==record.origin_time_ns))throw Error('Saved pulse-group origin differs.');
    const hashes=[reply.sidecar_manifest_sha256,reply.sidecar_data_sha256];
    if(!hashes.every(h=>h===null)&&!hashes.every(h=>typeof h==='string'&&/^[0-9a-f]{64}$/.test(h)))throw Error('Incomplete display derivative binding.');
    const peak=reply.panels[3].peak;if(!peak||!Object.is(peak.t,record.readout.peak_time_ns)||!Object.is(peak.v,record.readout.peak_V))throw Error('Original sampled peak changed.');
    SavedFocusPlots.draw($('plots'),reply.panels,reply.clock);
    const original=node('button','Download original saved plots');original.onclick=()=>download(context.job.name,'response/summary.html').catch(e=>notice(e.message,true));
    $('plots').append(original,node('p',reply.notes.join(' '),'muted'),node('small','Original artifact SHA256 · '+reply.summary_sha256+(hashes[0]?' · display derivative '+hashes[0]:'')));
  }catch(e){if(generation===plotGeneration&&context===result)$('plots').replaceChildren(node('p',e.message,'error'));}
}
function showGroup(){const generation=++plotGeneration,id=Number($('event').value),rs=primaryRecords(result.records,id),r=rs[Number($('group').value)],primary=rs.find(r=>['decay','primary'].includes(r.record_kind));$('event-identity').textContent='Initial primary '+id+(r.record_kind==='pulse'?' · pulse group '+r.group_id+' · origin '+r.origin_time_ns+' ns':primary?' · primary summary · '+primary.pulse_count+' pulse groups':r.zero_ge?' · known zero input':' · gamma response group 0');$('result-data').replaceChildren();const edep=r.truth_ge_edep_keV??r.deposited_energy_keV,charge=r.final_induced_keV??(r.zero_deposit?0:null),rec=r.readout?.reconstructed_energy_keV,metrics=node('div',undefined,'metrics');for(const [label,value]of [['Truth Edep · keV',edep],['Induced equivalent · keV',charge],['Reconstructed energy · keV',rec]]){const span=node('span',label);span.append(node('strong',metricValue(value)));metrics.append(span);} $('result-data').append(metrics,node('p',r.status||r.rejection_reason||(r.zero_deposit?'True zero deposition · no pulse group':r.record_kind==='pulse'?'Recorded pulse group':'Recorded primary')));const group=savedGroup(r),hasTrace=group&&(r.readout?.trace||result.traces.some(t=>(t.global_initial_id??t.event_id)===id&&t.group_id===group.id));$('plots').replaceChildren(node('p',hasTrace?'Loading original saved waveforms…':r.zero_deposit?'No pulse waveform for this zero-deposit primary.':'No saved waveform for this record. Pulse groups retain their scalar results.','muted'));if(hasTrace)loadPlots(result,id,group.id,generation);}
$('event').onchange=()=>showEvent();
$('group').onchange=showGroup;
$('setup').onclick=async()=>{try{const r=await api('/api/workflow/setup');$('setup-notice').textContent=r.checks.map(c=>(c.available?'✓ ':'Missing: ')+c.label).join(' · ')+' '+r.note;}catch(e){$('setup-notice').textContent=e.message;}};
$('check').onclick=async()=>{if(busy||active||!executableSelection())return;const version=selectionVersion;busy=true;checked=null;controls();try{const submitted=config(),serialized=JSON.stringify(submitted),batched=batchSelection();const reply=await api(batched?'/api/workflow/check-batches':'/api/workflow/check',batched?{request:batchRequest(submitted)}:{config:submitted});if(version!==selectionVersion||JSON.stringify(config())!==serialized){notice('Selection changed while Check was pending. Check the current setup.');return;}if(batched&&(reply.kind!=='local_scenario_batch_execution_v3'||reply.schema_version!==3||reply.execution_enabled!==true||typeof reply.check_id!=='string'))throw Error('Check did not authorize batch execution.');checked=reply;$('checked-plan').textContent=JSON.stringify(checked.resolved,null,2);notice(batched?'Exact count checked: '+submitted.primary_count+' initial primaries in '+checked.resolved.batching.batch_count+' serial batches. Run uses this checked plan.':'Legacy gamma configuration checked. Run uses its preserved 20-primary settings.');}catch(e){if(version===selectionVersion){checked=null;notice(e.message,true);}}finally{busy=false;controls();}};
$('start').onclick=async()=>{if(busy||active||!checked||!executableSelection())return;busy=true;controls();try{const job=await api('/api/workflow/start',{check_id:checked.check_id});showRun(job);checked=null;notice('Run reserved: '+job.name+'. Stages will appear as the backend observes them.');await poll();}catch(e){checked=null;notice(e.message,true);}finally{busy=false;controls();}};
$('save').onclick=()=>{if(busy||active||!executableSelection())return;try{const blob=new Blob([JSON.stringify(batchSelection()?batchRequest(config()):config(),null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='gesignal-configuration.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message,true);}};
function importedConfig(c,batched=false){const fields=['name','cryostat','detector','source','pose','primary_count','seed','threads','electronics'];if(!c||Array.isArray(c)||Object.keys(c).sort().join()!=fields.sort().join()||!c.electronics||Object.keys(c.electronics).sort().join()!=[...catalog.electronics_keys].sort().join())throw Error('Configuration fields do not match this application.');const source=catalog.sources.find(s=>s.id===c.source),detector=catalog.detectors.find(d=>d.id===c.detector);if(!source||source.available===false||!catalog.cryostats.some(x=>x.id===c.cryostat&&x.available)||!detector?.available||detector.sources&&!detector.sources.includes(c.source)||source.pose!==c.pose||(batched?!Number.isSafeInteger(c.primary_count)||c.primary_count<1||source.id==='mono_gamma_662_axis_v1':!source.counts.includes(c.primary_count))||![1,2].includes(c.threads)||!Number.isInteger(c.seed)||c.seed<1||c.seed>2147483646||typeof c.name!=='string'||(!batched&&source.fixed_seed!=null&&c.seed!==source.fixed_seed))throw Error('The imported setup is unavailable. No selection was replaced.');for(const key of catalog.electronics_keys){const value=c.electronics[key];if(key==='peak_policy'?typeof value!=='string':key.startsWith('peak_gate_')?value!==null&&(typeof value!=='number'||!Number.isFinite(value)):typeof value!=='number'||!Number.isFinite(value))throw Error('Imported electronics values have invalid types.');}if((c.electronics.peak_gate_start_ns===null)!==(c.electronics.peak_gate_end_ns===null))throw Error('A peak gate requires both boundaries.');return c;}
function importedRequest(value){if(value?.kind==='local_scenario_batch_request_v2'){if(Object.keys(value).sort().join()!=='kind,schema_version,selection'||value.schema_version!==2)throw Error('Batch request fields do not match this application.');return importedConfig(value.selection,true);}return importedConfig(value);}
$('load').onclick=()=>{if(!busy&&!active)$('import').click();};$('import').onchange=async()=>{const generation=++importGeneration,version=selectionVersion;try{if(busy||active)throw Error('Wait for the current action before loading a configuration.');const f=$('import').files[0];if(!f||f.size>65536)throw Error('Choose a configuration JSON under 64 KiB.');const c=importedRequest(JSON.parse(await f.text()));if(generation!==importGeneration||version!==selectionVersion||busy||active)throw Error('Selection or activity changed while loading. Choose the configuration file again.');for(const id of ['name','cryostat','detector','source','threads'])$(id).value=c[id];detectorChanged();$('seed').value=c.seed;$('count').value=String(c.primary_count);$('pose').value=c.pose;for(const key of catalog.electronics_keys)$('setting-'+key).value=c.electronics[key]??'';$('use-peak-gate').checked=c.electronics.peak_gate_start_ns!==null;gateFields();invalidate();notice('Configuration loaded. Check plan validates the admitted setup.');}catch(e){if(generation===importGeneration)notice(e.message,true);}finally{if(generation===importGeneration)$('import').value='';}};
(async()=>{try{catalog=await api('/api/workflow/catalog');options('cryostat',catalog.cryostats);options('detector',detectorItems(),true);$('detector').value='AK02';electronics();$('numerics').textContent=catalog.numerics;$('setup-limit').textContent=catalog.setup_limit||'';detectorChanged();stageList();for(const id of ['cryostat','pose','count','seed','threads','name'])$(id).addEventListener('input',invalidate);$('detector').onchange=detectorChanged;$('source').onchange=sourceChanged;await poll();setInterval(poll,2500);}catch(e){notice(e.message,true);$('check').disabled=true;}})();
