import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const code=fs.readFileSync('tools/viewer_navigation.js','utf8');
const c=vm.createContext({URLSearchParams,location:{search:''}});vm.runInContext(code,c);
const query=s=>vm.runInContext(`parseViewerQuery(${JSON.stringify(s)})`,c);
assert.equal(query('?model=SAP22&event=0&group=0').event,0);
assert.equal(query('?event=9999').event,9999);
for(const s of ['?event=','?event=-1','?event=10000','?event=1e2','?event=01','?event=1.5','?event=0&event=1','?model=unknown','?foo=1','?group=0','?event=213&group=9007199254740992'])assert.ok(query(s).invalid,s);
for(const s of ['', '?model=AK02&event=213&group=0','?model=SAP22&event=0'])assert.equal(query(s).invalid,'',s);
const template=fs.readFileSync('tools/geometry_events.html','utf8');
vm.runInContext(template.match(/<script id="selection-core">([\s\S]*?)<\/script>/)[1],c);
let value=null,clears=0; c.clear=()=>{value=null;clears++};const gate=vm.runInContext('selectionGate(clear)',c);
let resolveOld,rejectOld;
const old=gate.run(()=>new Promise(r=>resolveOld=r),v=>value=v,e=>value=e.message);
await gate.run(async()=>213,v=>value=v,e=>value=e.message);resolveOld(0);await old;assert.equal(value,213);
const failed=gate.run(()=>new Promise((r,j)=>rejectOld=j),v=>value=v,e=>value=e.message);
await gate.run(async()=>9999,v=>value=v,e=>value=e.message);rejectOld(Error('old failure'));await failed;assert.equal(value,9999);
gate.invalidate();assert.equal(value,null);assert.equal(clears,5);
console.log(JSON.stringify({status:'passed',query_cases:16,late_success_and_failure:true,zero_preserved:true}));
